version: '3'
services:
  pyrogram_bot:
    build: ./
    container_name: pyrogram_bot
    working_dir: /app
    volumes:
      - "./:/app"

  postgres:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - "./sql.sql:/docker-entrypoint-initdb.d/init.sql"

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres


